cover page created .
iiitv/iiitvcc pull request #5
Opened 2020-09-01 15:14 UTC by nlok5923

you can view the cover page : https://youthful-liskov-ec4953.netlify.app/

2020-09-02 04:24 UTC, nlok5923 commented
@AmanRaj1608 sir the cover page i has created is not responsive so sir for it. Will you make another issue to create cover page responsive or in this pr only i has to make it responsive.

2020-09-04 02:45 UTC, nlok5923 commented
@AmanRaj1608 sir please review this pull request.

2020-09-20 15:25 UTC, AmanRaj1608 requested changes

2020-09-20 15:25 UTC, AmanRaj1608 commented on src/components/Home/Cover/Cover.css
> +.trans-btn {
Can we have some hover effect.

2020-09-20 15:27 UTC, AmanRaj1608 commented
Hi, @nlok5923 sorry for the late review,
It's okay I will create another issue for responsive design give it a try if you can fix it.

2020-09-20 15:35 UTC, nlok5923 commented
@AmanRaj1608 sir added the hover effect feature.

2020-09-20 15:50 UTC, AmanRaj1608 approved these changes

2020-09-20 15:50 UTC, merged