made cover page responsive
iiitv/iiitvcc pull request #7
Opened 2020-09-20 17:17 UTC by nlok5923

fixes : #6

2020-09-20 17:29 UTC, nlok5923 commented
@AmanRaj1608 please review this pull request.

2020-09-20 17:50 UTC, AmanRaj1608 requested changes
See the comment

2020-09-20 17:50 UTC, AmanRaj1608 commented
- Set the home height to full screen using `90vh`.
- Remove the gap between the buttons as per design.
- font-weight not matching as per design. In small screens decrease the font size.
- Also set the navbar color to the same as you have used in the home section.

Current view
![image](https://user-images.githubusercontent.com/42104907/93718076-5309b500-fb97-11ea-87a6-c3a3a2f394b8.png)

Expected 
![image](https://user-images.githubusercontent.com/42104907/93718116-92d09c80-fb97-11ea-80c4-b874aab7d320.png)

2020-09-20 17:52 UTC, nlok5923 commented
Okay sir I am working on it.

2020-09-22 17:04 UTC, AmanRaj1608 requested changes
On small devices don't hardcode px values.
It's better to use `vw` , `%` so that it adjusts for many devices instead of hardcoding values.

2020-09-22 17:04 UTC, AmanRaj1608 commented on src/components/Home/Cover/Cover.css
>  @media only screen and (max-width: 900px) {
The breakpoint is 900px
It doesnt look goods on medium-size device as 
From this 

![image](https://user-images.githubusercontent.com/42104907/93913923-621d6e00-fd23-11ea-8947-9fda770fd9d8.png)

![image](https://user-images.githubusercontent.com/42104907/93913931-66e22200-fd23-11ea-9d15-40134f40e92a.png)

2020-09-22 17:32 UTC, nlok5923 commented on src/components/Home/Cover/Cover.css
> +  width: 400px;
sir 490&596 will be too big i think .
![Screenshot (1347)](https://user-images.githubusercontent.com/56120084/93916793-e984c600-fcbe-11ea-9ceb-bf897bda0bba.png)

2020-09-22 18:09 UTC, nlok5923 commented
@AmanRaj1608 sir please review the changes.

2020-09-23 09:31 UTC, yashshah2820 commented on src/components/Home/Cover/Cover.css
>  #cover-display {
add a link space between add proper formatting wherever needed

2020-09-23 09:32 UTC, yashshah2820 requested changes
apply proper formatting between different css classes.

2020-09-23 10:05 UTC, yashshah2820 requested changes
formatting required in Cover.css

2020-09-23 10:05 UTC, yashshah2820 commented on src/components/Header/Header.css
> +@media (max-width: 860px) {
still not formatted 🤕

2020-09-23 10:05 UTC, yashshah2820 commented on src/components/Home/Cover/Cover.css
>  #flex-container {
add a line here

2020-09-23 10:05 UTC, yashshah2820 commented on src/components/Home/Cover/Cover.css
>  .display-head {
add a line here

2020-09-23 10:09 UTC, nlok5923 commented on src/components/Home/Cover/Cover.css
>  .display-head {
Sorry sir i thought something different before.

2020-09-23 10:14 UTC, yashshah2820 reviewed
still not formatted, take a look 😞

2020-09-23 10:14 UTC, yashshah2820 commented on src/components/Header/Header.css
> +.overlay .close {
add a line here

2020-09-23 10:14 UTC, yashshah2820 commented on src/components/Home/Cover/Cover.css
>  .display-heading {
add a line here

2020-09-23 10:14 UTC, yashshah2820 commented on src/components/Home/Cover/Cover.css
> +.manage-goodline {
add a line here

2020-09-23 10:14 UTC, yashshah2820 commented on src/components/Home/Cover/Cover.css
>  .good-line {
add a line here

2020-09-23 10:14 UTC, yashshah2820 commented on src/components/Home/Cover/Cover.css
>  .inf-btn {
add a line here

2020-09-23 10:14 UTC, yashshah2820 commented on src/components/Home/Cover/Cover.css
>  .trans-btn {
add a line here

2020-09-23 10:14 UTC, yashshah2820 commented on src/components/Home/Cover/Cover.css
> +.trans-btn:hover {
add a line here

2020-09-23 10:14 UTC, yashshah2820 commented on src/components/Home/Cover/Cover.css
> +@media only screen and (max-width: 1050px) {
add a line here

2020-09-23 16:55 UTC, AmanRaj1608 approved these changes

2020-09-23 16:55 UTC, merged